@startuml
left to right direction

actor User

rectangle "COLORS Web Application" {
  usecase "Log In" as UC1
  usecase "Search Color" as UC2
  usecase "Add Color" as UC3
  usecase "Log Out" as UC4
}

User --> UC1
User --> UC2
User --> UC3
User --> UC4

@enduml
